version: '3'
networks:
    dmad_private_network:
        external: true

services:
    unbound:
        image: "klutchell/unbound"
        container_name: unbound
        restart: unless-stopped
        hostname: "unbound"
        networks:
            dmad_private_network:
                ipv4_address: 10.2.0.200
        #        deploy:
        #            resources:
        #                limits:
        #                    cpus: "1"
        #                    memory: 512M
        healthcheck:
            test: [ "CMD", "dig", "@127.0.0.1", "google.com" ]
            interval: 30s
            timeout: 5s
            retries: 3

    pihole:
        image: "pihole/pihole:latest"
        container_name: pihole
        restart: unless-stopped
        hostname: pihole
        dns:
            - 127.0.0.1
            - 10.2.0.200
        env_file:
            - .env
        volumes:
            - "./etc-pihole/:/etc/pihole/"
            - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
        cap_add:
            - NET_ADMIN
        networks:
            dmad_private_network:
                ipv4_address: 10.2.0.100
        healthcheck:
            test: [ "CMD", "dig", "@127.0.0.1", "google.com" ]
            interval: 30s
            timeout: 5s
            retries: 3

    wg-easy:
        image: "ghcr.io/wg-easy/wg-easy:14"
        container_name: wg-easy
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - .:/etc/wireguard
        ports:
            - "51820:51820/udp"
            #- "127.0.0.1:51821:51821/tcp" # By default, mapping port 51821 is disabled, allowing only services on the same docker network to be called for safety.
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.ip_forward=1
            - net.ipv4.conf.all.src_valid_mark=1
        dns:
            - 10.2.0.100
            - 10.2.0.200
        networks:
            dmad_private_network:
                ipv4_address: 10.2.0.3
        depends_on:
            - pihole
            - unbound
